name: Feature Pipeline (Hourly)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pymongo python-dotenv pandas hopsworks

      - name: Run feature pipeline
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
        run: |
          python feature_pipeline.py